FROM node:slim AS build

WORKDIR /opt/app

COPY ./package.json /opt/app/package.json
COPY ./package-lock.json /opt/app/package-lock.json
RUN npm install

COPY ./src /opt/app/src
COPY ./config /opt/app/config
COPY ./webpack.config.js /opt/app/webpack.config.js
COPY ./.babelrc /opt/app/.babelrc
COPY ./nginx.conf /opt/app/nginx.conf

RUN npm run build

FROM nginx

COPY --from=build /opt/app/dist /usr/share/nginx/html
COPY --from=build /opt/app/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
